### ISSUE TITLE
Absolute or relative path for filename

### ISSUE THREAD

**Issue by eitoball** [eitoball/rubocop-checkstyle_formatter#9]
Since 0.2.0, filename is relative to project path, but this change is causing troubles for some Jenkins plugins such as violation plugin. Need to find way to be able to choose relative or absolute path for filename. See #8.

**Comment by yld** [comment]
Could you publish this fix? Github repositories are not very usable in gemspec definition.

Thank you for your hard work.

**Comment by keith-roberts** [comment]
Is this a similar issue here:

As I only build on the master Jenkins node this has only ever been used for freestyle projects:

/var/lib/jenkins/workspace/test/

and

/var/lib/jenkins/workspace/test@script/

gets used as the root directory when I create a pipeline project.

I have deleted the /var/lib/jenkins/workspace/test/ directory and created a symlink to:

/var/lib/jenkins/workspace/test@script

So that now points the checkstyle plugin the pipeline's workspace and all seems to be working fine now.

https://issues.jenkins-ci.org/browse/JENKINS-42095

**Comment by eitoball** [comment]
This issue should be fixed by 338ce2d64a587011fda28f7b4c9b25afdf2b3826. If you define environment variable RUBOCOP_CHECKSTYLE_FORMATTER_ABSOLUTE_PATH, formatter should output absolute path.
